#import the base image first(make sure it is lightweight because we can't use the multistage docker build in here, even if we use it ,it doesn't make any diffrence )
FROM nginx:alpine
#copy the code into the container
COPY frontend/ /usr/share/nginx/html
#now copy the nginx configuration because we won't be chnaging the nginx config in the running container , because we can't do it everytiem we spin up the frontend container manually so we copy nginx.config
COPY nginx.conf /etc/nginx/conf.d/default.conf
#expose the port(nginx default port)
EXPOSE 80
#command to keep it running
CMD ["nginx", "-g", "daemon off;"]


